# Generated by Django 5.2.8 on 2025-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_bonus_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
