# Generated by Django 5.2.8 on 2025-11-19 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_welcome_bonus_claimed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mines_count', models.IntegerField()),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('mine_positions', models.JSONField()),
                ('revealed_tiles', models.JSONField(default=list)),
                ('current_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_minesga_user_id_8811f7_idx'), models.Index(fields=['status', '-created_at'], name='api_minesga_status_6fdb61_idx')],
            },
        ),
    ]
