# Generated by Django 5.2.8 on 2025-11-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_minesgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mines_nonce',
            field=models.IntegerField(default=0),
        ),
    ]
