# Generated by Django 5.2.8 on 2025-11-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_mines_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_client_seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
