# Generated by Django 5.2.8 on 2025-11-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_current_client_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seed_games_played',
            field=models.IntegerField(default=0),
        ),
    ]
