# Generated by Django 5.2.8 on 2025-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_seed_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_server_seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_server_seed_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
