# Generated by Django 5.2.8 on 2025-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_next_server_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mines_best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_biggest_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='mines_total_wagered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
