# Generated by Django 5.2.8 on 2025-11-24 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_mines_best_streak_profile_mines_biggest_win_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keno_best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_biggest_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='keno_total_wagered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='KenoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numbers_selected', models.JSONField()),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('drawn_numbers', models.JSONField(default=list)),
                ('matches', models.IntegerField(default=0)),
                ('current_multiplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keno_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_kenogam_user_id_597edb_idx'), models.Index(fields=['status', '-created_at'], name='api_kenogam_status_c6c46a_idx')],
            },
        ),
    ]
