# Generated by Django 5.2.8 on 2025-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_keno_best_streak_profile_keno_biggest_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_daily_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
