# Generated by Django 5.2.8 on 2025-12-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_last_daily_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ad_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
